#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 24 18:36:50 2020

@author: alexandrubujor
"""

''' Nucleotide Counter without a built-in file opener'''

nucleotides =  ['A', 'C', 'G', 'T']

s = 'AATAGAAATCCAATGGAGCACCAGACCGTTTAAGAGTAAGTCATCAAGGTGACGACTTTCCAGTCCTCGCATGACAGTAATTGCGCTACGTGCCTTGGGGTGCCGCCATCTTTTCTTATCTCGTAAATAAGTCCGCAAACAAGTCCAGGGAGGAGCGGTCGGAGATAGCTCGGCCGCTTATAGCACCCTCAGTTACAGCGGAACTTACGCGGGGGGTAGTCGCGCACGATCAGATCCCAGGTTATCATTTACCTCTTACAGGCTGTTCTGAGCTCAACTGGCTCCAACTCGTCGCGTCGTAACTTAATGCAGGGTGGATTGAATATGCATACTGGCATCGCGTGGAGCCCCCGTCAGGGCACCGCCGCGCTGGGTGCAGAACCTCGTAGTAAGTCGTTTTTCGTGGCTAGGAGCAAATAGTGTGCATCCGCTGTGTTAAGCATGAGGCGGGCGCGTGTTATAGACTGTCGTAATGGGGGATCCTTCTTGGCTCCGACCCATTGAACCGGTCAACTGTTGGACGTACTTGGGTTATCCAATATGACTAGTAAACAGAGACGAATAACGAAATGCTCGAAGTTTTGAGGAAATGGTTTAAATTCCCGTAAGTTGGGTGGAAGTGTGAACTTTTGGTAGCACTCTATTATATCGCGACCTGTTGTTAGTGGATAGGAGGACACAACCGTGACAATTGCCACTCTACATCAAGTGGCGTCTCCAATACCCGAATTTCTGAGGATGCGTGATTTGACGTTGAAGACCTATCAGTCTAGTGATTCGAGCTGCTCGATACCCAAACACGACGATTCCCTTTGTAAGACTTTATTTTCAACCCTAATAATTGAAGGTCGCTCCGTTGGGAAAACATGAGCGGTCTCGTGTGAGAGGACAATATATTTATGGTTTACCTGTTTGTTATAGCAGCACAGATACCGGAGCGTCTGAGCC'


perechi_nucl = list(sorted(set(s))) # I want it to show it the alphabetic order

dict = {'A':0,'C':0,'G':0,'T':0} # Built a dictionary to count the nucleotides


for char in s:
    dict[char] = s.count(char) # Dict iterator counting nucleotides in the string

print(dict['A'], dict['C'], dict['G'], dict['T']) # Made it print only the number - ROSALIND.info answer template